"""Card and board content for Campfire v1."""

from __future__ import annotations

from sov_engine.models import (
    Card,
    CardType,
    DealCard,
    EventCard,
    Space,
    SpaceKind,
    VoucherCard,
)


def build_board() -> list[Space]:
    """Create the 16-space Campfire board."""
    return [
        Space(0, "Campfire", SpaceKind.CAMPFIRE, "Safe. Collect 1 coin if you pass through."),
        Space(1, "Workshop", SpaceKind.WORKSHOP, "Pay 2 coins to gain 1 Upgrade."),
        Space(2, "Market", SpaceKind.MARKET, "Buy or sell 1 resource at Market Price."),
        Space(3, "Rumor Mill", SpaceKind.RUMOR_MILL, "Draw an Event card."),
        Space(4, "Trade Dock", SpaceKind.TRADE_DOCK, "Propose a trade with any player."),
        Space(5, "Festival", SpaceKind.FESTIVAL, "Donate 1 coin to gain +1 Reputation."),
        Space(6, "Trouble", SpaceKind.TROUBLE, "Lose 1 coin OR lose 1 Reputation."),
        Space(7, "Help Desk", SpaceKind.HELP_DESK, "Give another player 1 coin; both gain +1 Rep."),
        Space(8, "Mint", SpaceKind.MINT, "Gain 2 coins from the bank."),
        Space(9, "Rumor Mill", SpaceKind.RUMOR_MILL, "Draw an Event card."),
        Space(10, "Builder", SpaceKind.BUILDER, "Pay 3 coins for 1 Upgrade. Requires Rep >= 3."),
        Space(11, "Faucet", SpaceKind.FAUCET, "Gain 1 coin from the bank."),
        Space(12, "Trade Dock", SpaceKind.TRADE_DOCK, "Propose a trade with any player."),
        Space(13, "Taxman", SpaceKind.TAXMAN, "Pay 1 coin. Can't pay? Lose 1 Rep instead."),
        Space(14, "Commons", SpaceKind.COMMONS, "Vote: if majority agrees, everyone gains 1 coin."),
        Space(15, "Crossroads", SpaceKind.CROSSROADS, "Draw a Deal card. Accept or pass."),
    ]


def build_event_deck() -> list[Card]:
    """Create the 28 Event cards (20 Campfire + 8 Market-shift for Town Hall)."""
    return [
        # --- Original 10 ---
        EventCard(
            id="evt_01",
            name="Supply Delay",
            card_type=CardType.EVENT,
            description="Upgrades cost +1 coin this round.",
            flavor="The shipment's late. Again.",
            effect_id="supply_delay",
        ),
        EventCard(
            id="evt_02",
            name="Boom Town",
            card_type=CardType.EVENT,
            description="Every player gains 1 coin.",
            flavor="Trade is good. Everyone's eating.",
            effect_id="boom_town",
        ),
        EventCard(
            id="evt_03",
            name="Storm",
            card_type=CardType.EVENT,
            description="Every player pays 1 coin or loses 1 Rep.",
            flavor="Batten down the hatches.",
            effect_id="storm",
        ),
        EventCard(
            id="evt_04",
            name="Rumor",
            card_type=CardType.EVENT,
            description="You lose 1 Rep -- unless someone vouches for you.",
            flavor="People are talking...",
            effect_id="rumor",
        ),
        EventCard(
            id="evt_05",
            name="Big Order",
            card_type=CardType.EVENT,
            description="Market prices +1 this round.",
            flavor="A caravan just arrived with deep pockets.",
            effect_id="big_order",
        ),
        EventCard(
            id="evt_06",
            name="Festival of Plenty",
            card_type=CardType.EVENT,
            description="Next 2 Festival landings give +2 Rep instead of +1.",
            flavor="The whole town is celebrating.",
            effect_id="festival_of_plenty",
        ),
        EventCard(
            id="evt_07",
            name="Swindle",
            card_type=CardType.EVENT,
            description="You may force one voucher redemption NOW.",
            flavor="Time to collect.",
            effect_id="swindle",
        ),
        EventCard(
            id="evt_08",
            name="Windfall",
            card_type=CardType.EVENT,
            description="You gain 3 coins.",
            flavor="Lucky day.",
            effect_id="windfall",
        ),
        EventCard(
            id="evt_09",
            name="Drought",
            card_type=CardType.EVENT,
            description="No one can buy at the Market this round.",
            flavor="Nothing on the shelves.",
            effect_id="drought",
        ),
        EventCard(
            id="evt_10",
            name="Trust Crisis",
            card_type=CardType.EVENT,
            description="Players with Rep < 3 lose 1 more Rep.",
            flavor="When trust is low, it falls further.",
            effect_id="trust_crisis",
        ),
        # --- New 10: human-voice cards ---
        EventCard(
            id="evt_11",
            name="Lost Wallet",
            card_type=CardType.EVENT,
            description="You can't trade this turn -- unless someone lends you 1 coin.",
            flavor="Has anyone seen a small leather pouch?",
            effect_id="lost_wallet",
        ),
        EventCard(
            id="evt_12",
            name="Good News Travels",
            card_type=CardType.EVENT,
            description="If you helped someone last round, gain 2 coins now.",
            flavor="Word got around about what you did.",
            effect_id="good_news",
        ),
        EventCard(
            id="evt_13",
            name="Awkward Favor",
            card_type=CardType.EVENT,
            description="Ask any player to cover 2 coins for you. You owe them 3 later.",
            flavor="Hey... got a minute?",
            effect_id="awkward_favor",
        ),
        EventCard(
            id="evt_14",
            name="Found a Shortcut",
            card_type=CardType.EVENT,
            description="Gain 3 coins, but lose 1 Rep. People noticed.",
            flavor="Nobody saw... right?",
            effect_id="shortcut",
        ),
        EventCard(
            id="evt_15",
            name="Community Dinner",
            card_type=CardType.EVENT,
            description="Everyone may donate 1 coin. Each donor gains +1 Rep.",
            flavor="Bring something to share.",
            effect_id="community_dinner",
        ),
        EventCard(
            id="evt_16",
            name="Old Friend",
            card_type=CardType.EVENT,
            description="Pick a player. You each gain +1 Rep.",
            flavor="It's been too long.",
            effect_id="old_friend",
        ),
        EventCard(
            id="evt_17",
            name="Broken Bridge",
            card_type=CardType.EVENT,
            description="Skip your next move. Stay where you are.",
            flavor="Road's out. Might as well make camp.",
            effect_id="broken_bridge",
        ),
        EventCard(
            id="evt_18",
            name="Harvest Moon",
            card_type=CardType.EVENT,
            description="The player with the fewest coins gains 2 coins.",
            flavor="The land provides for those who need it most.",
            effect_id="harvest_moon",
        ),
        EventCard(
            id="evt_19",
            name="Tall Tale",
            card_type=CardType.EVENT,
            description="Gain 1 Rep. But if you're already above 7, lose 1 instead.",
            flavor="Some stories are too good to be true.",
            effect_id="tall_tale",
        ),
        EventCard(
            id="evt_20",
            name="Lucky Find",
            card_type=CardType.EVENT,
            description="Draw another Event immediately.",
            flavor="What's this?",
            effect_id="lucky_find",
        ),
        # --- Market-shift events (Town Hall) ---
        EventCard(
            id="evt_21",
            name="Bumper Harvest",
            card_type=CardType.EVENT,
            description="Food floods the market. Food price -1 this round.",
            flavor="More tomatoes than anyone knows what to do with.",
            effect_id="market_food_down",
        ),
        EventCard(
            id="evt_22",
            name="Logging Ban",
            card_type=CardType.EVENT,
            description="Wood gets scarce. Wood price +1 this round.",
            flavor="The council says: no more chopping until spring.",
            effect_id="market_wood_up",
        ),
        EventCard(
            id="evt_23",
            name="Tinker's Arrival",
            card_type=CardType.EVENT,
            description="A traveling tinker sells cheap. Tools price -1 this round.",
            flavor="Step right up! Everything must go!",
            effect_id="market_tools_down",
        ),
        EventCard(
            id="evt_24",
            name="Trade Caravan",
            card_type=CardType.EVENT,
            description="The caravan restocks. +2 to each supply pool.",
            flavor="Fresh goods from the valley.",
            effect_id="market_restock",
        ),
        EventCard(
            id="evt_25",
            name="Warehouse Fire",
            card_type=CardType.EVENT,
            description="Lose 2 from each supply pool. Prices don't change.",
            flavor="Somebody left a lantern burning.",
            effect_id="market_fire",
        ),
        EventCard(
            id="evt_26",
            name="Feast Day",
            card_type=CardType.EVENT,
            description="Everyone eats! Remove 1 Food from each player who has it.",
            flavor="The whole town gathers. Bring what you've got.",
            effect_id="market_feast",
        ),
        EventCard(
            id="evt_27",
            name="Tool Shortage",
            card_type=CardType.EVENT,
            description="Tools price +1 this round. Upgrades cost +1 coin.",
            flavor="Everything's breaking and nobody can fix it.",
            effect_id="market_tools_up",
        ),
        EventCard(
            id="evt_28",
            name="Good Rains",
            card_type=CardType.EVENT,
            description="All prices -1 this round. The land provides.",
            flavor="The rivers are full and the fields are green.",
            effect_id="market_all_down",
        ),
    ]


def build_deal_deck() -> list[Card]:
    """Create the 22 Deal/Voucher cards (12 Deals + 10 Vouchers)."""
    deals: list[Card] = [
        # --- Original 5 Deals ---
        DealCard(
            id="deal_01",
            name="Supply Run",
            card_type=CardType.DEAL,
            description="Deliver 3 coins to any player within 2 rounds.",
            reward_coins=0,
            reward_rep=2,
            penalty_rep=1,
            deadline_rounds=2,
        ),
        DealCard(
            id="deal_02",
            name="Builder's Promise",
            card_type=CardType.DEAL,
            description="Build 1 Upgrade within 3 rounds.",
            reward_coins=1,
            reward_rep=1,
            penalty_rep=1,
            deadline_rounds=3,
        ),
        DealCard(
            id="deal_03",
            name="Generosity Pledge",
            card_type=CardType.DEAL,
            description="Give 1 coin to each other player.",
            reward_coins=0,
            reward_rep=3,
            penalty_rep=2,
            deadline_rounds=2,
        ),
        DealCard(
            id="deal_04",
            name="Market Watcher",
            card_type=CardType.DEAL,
            description="Buy or sell at Market twice within 4 rounds.",
            reward_coins=2,
            reward_rep=1,
            penalty_rep=1,
            deadline_rounds=4,
        ),
        DealCard(
            id="deal_05",
            name="Peacekeeper",
            card_type=CardType.DEAL,
            description="Help someone at Help Desk within 3 rounds.",
            reward_coins=0,
            reward_rep=2,
            penalty_rep=1,
            deadline_rounds=3,
        ),
        # --- New 5 Deals: human-voice ---
        DealCard(
            id="deal_06",
            name="Spot Me",
            card_type=CardType.DEAL,
            description="Give 2 coins to a player now. They owe you 3 next round.",
            flavor="I'm good for it, I swear.",
            reward_coins=3,
            reward_rep=1,
            penalty_rep=1,
            deadline_rounds=2,
        ),
        DealCard(
            id="deal_07",
            name="Two-Person Discount",
            card_type=CardType.DEAL,
            description="Find a partner. You both pay 1 coin, you both gain 2.",
            flavor="Bulk deal. Split it?",
            reward_coins=2,
            reward_rep=0,
            penalty_rep=1,
            deadline_rounds=1,
        ),
        DealCard(
            id="deal_08",
            name="Mutual Aid Pact",
            card_type=CardType.DEAL,
            description="Pick a partner. Next Trouble, the other helps for free.",
            flavor="I've got your back if you've got mine.",
            reward_coins=0,
            reward_rep=2,
            penalty_rep=2,
            deadline_rounds=4,
        ),
        DealCard(
            id="deal_09",
            name="Reputation for Hire",
            card_type=CardType.DEAL,
            description="Give 1 coin to a player. They give you +1 Rep at Help Desk.",
            flavor="Put in a good word for me?",
            reward_coins=0,
            reward_rep=1,
            penalty_rep=1,
            deadline_rounds=2,
        ),
        DealCard(
            id="deal_10",
            name="The Long Game",
            card_type=CardType.DEAL,
            description="Don't spend any coins for 2 full rounds.",
            flavor="Patience pays. Eventually.",
            reward_coins=4,
            reward_rep=1,
            penalty_rep=1,
            deadline_rounds=2,
        ),
        # --- Resource-native deals (Town Hall) ---
        DealCard(
            id="deal_11",
            name="Soup Kitchen",
            card_type=CardType.DEAL,
            description="Donate 1 Food to any player. +1 Rep for you.",
            flavor="Nobody goes hungry on my watch.",
            reward_coins=0,
            reward_rep=1,
            penalty_rep=0,
            deadline_rounds=3,
        ),
        DealCard(
            id="deal_12",
            name="Lend Me Your Hammer",
            card_type=CardType.DEAL,
            description="Loan 1 Tools for a round. Returned = +1 Rep. Kept = they lose 2 Rep.",
            flavor="I just need it for the afternoon.",
            reward_coins=0,
            reward_rep=1,
            penalty_rep=2,
            deadline_rounds=2,
        ),
    ]
    vouchers: list[Card] = [
        # --- Original 5 Vouchers ---
        VoucherCard(
            id="vouch_01",
            name="Small Loan",
            card_type=CardType.VOUCHER,
            description="I owe you 2 coins. Due in 3 rounds.",
            face_value=2,
            deadline_rounds=3,
            default_penalty_rep=2,
        ),
        VoucherCard(
            id="vouch_02",
            name="Big Loan",
            card_type=CardType.VOUCHER,
            description="I owe you 4 coins. Due in 4 rounds.",
            face_value=4,
            deadline_rounds=4,
            default_penalty_rep=3,
        ),
        VoucherCard(
            id="vouch_03",
            name="Favor Owed",
            card_type=CardType.VOUCHER,
            description="I owe you 1 coin and a free Help Desk. Due in 3 rounds.",
            face_value=1,
            deadline_rounds=3,
            default_penalty_rep=2,
        ),
        VoucherCard(
            id="vouch_04",
            name="Trade Credit",
            card_type=CardType.VOUCHER,
            description="I owe you 3 coins, but only at Trade Dock.",
            face_value=3,
            deadline_rounds=4,
            default_penalty_rep=2,
        ),
        VoucherCard(
            id="vouch_05",
            name="Blank Voucher",
            card_type=CardType.VOUCHER,
            description="We'll figure out the terms. (1-5 coins, 1-5 rounds.)",
            face_value=0,
            deadline_rounds=0,
            default_penalty_rep=0,
            negotiable=True,
        ),
        # --- New 5 Vouchers: human-voice ---
        VoucherCard(
            id="vouch_06",
            name="Quick Cash",
            card_type=CardType.VOUCHER,
            description="I need 1 coin now. I'll pay you 2 next round. Promise.",
            face_value=2,
            deadline_rounds=1,
            default_penalty_rep=2,
        ),
        VoucherCard(
            id="vouch_07",
            name="Builder's Tab",
            card_type=CardType.VOUCHER,
            description="Cover my upgrade cost (2 coins). I'll pay 3 back.",
            face_value=3,
            deadline_rounds=3,
            default_penalty_rep=2,
        ),
        VoucherCard(
            id="vouch_08",
            name="Festival Fund",
            card_type=CardType.VOUCHER,
            description="Lend me 1 coin for Festival. I'll repay with interest.",
            face_value=2,
            deadline_rounds=2,
            default_penalty_rep=1,
        ),
        VoucherCard(
            id="vouch_09",
            name="Emergency Loan",
            card_type=CardType.VOUCHER,
            description="I'm broke. Lend me 3 coins. I'll pay 3 back. No interest, just trust.",
            face_value=3,
            deadline_rounds=3,
            default_penalty_rep=3,
        ),
        VoucherCard(
            id="vouch_10",
            name="Handshake Deal",
            card_type=CardType.VOUCHER,
            description="We agree on terms right now. (Negotiable, like Blank Voucher.)",
            face_value=0,
            deadline_rounds=0,
            default_penalty_rep=0,
            negotiable=True,
        ),
    ]
    return deals + vouchers
